"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase";
import styles from "./AdminCourseManager.module.css";

type Course={id:string;course_key:string;name:string;description:string;icon:string;category:string;active:boolean;diagnostic_available:boolean;is_essential:boolean;mandatory_days:number|null};
type CourseForm={id:string|null;course_key:string;name:string;description:string;icon:string;category:string;active:boolean;diagnostic_available:boolean};
type CatalogFilter="all"|"active"|"inactive"|"essential";
const emptyForm:CourseForm={id:null,course_key:"",name:"",description:"",icon:"📚",category:"General",active:true,diagnostic_available:false};
function slugify(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"");}
function friendlyError(error:unknown){const m=error instanceof Error?error.message:typeof error==="object"&&error&&"message" in error?String((error as {message?:unknown}).message??""):"";if(m.includes("Course key cannot be changed"))return"El identificador interno de un curso existente no puede cambiarse.";if(m.includes("Essential courses are system-managed"))return"Los cursos de Formación esencial son administrados por el sistema.";if(m.includes("Admin role required"))return"Solo una cuenta administradora puede modificar el catálogo.";return m||"No se pudo guardar el curso.";}

export default function AdminCourseManager(){
 const[courses,setCourses]=useState<Course[]>([]);const[form,setForm]=useState<CourseForm>(emptyForm);const[selectedId,setSelectedId]=useState<string|null>(null);const[search,setSearch]=useState("");const[filter,setFilter]=useState<CatalogFilter>("all");const[keyTouched,setKeyTouched]=useState(false);const[canManage,setCanManage]=useState(false);const[ready,setReady]=useState(false);const[saving,setSaving]=useState(false);const[message,setMessage]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);
 async function load(preferredId?:string|null){setError(null);const{data:sessionData}=await supabase.auth.getSession();const session=sessionData.session;if(!session){setReady(true);return;}const{data:adminRole,error:roleError}=await supabase.from("user_roles").select("role").eq("user_id",session.user.id).eq("role","admin").maybeSingle();if(roleError)throw roleError;if(!adminRole){setCanManage(false);setReady(true);return;}setCanManage(true);const{data,error:courseError}=await supabase.from("courses").select("id, course_key, name, description, icon, category, active, diagnostic_available, is_essential, mandatory_days").order("is_essential",{ascending:true}).order("name");if(courseError)throw courseError;const loaded=(data??[]) as Course[];setCourses(loaded);const target=loaded.find(c=>c.id===(preferredId??selectedId));if(target)selectCourse(target);setReady(true);}
 useEffect(()=>{load().catch(e=>{setError(friendlyError(e));setReady(true);});},[]);
 const categories=useMemo(()=>Array.from(new Set(courses.map(c=>c.category).filter(Boolean))).sort((a,b)=>a.localeCompare(b,"es")),[courses]);
 const visibleCourses=useMemo(()=>{const term=search.trim().toLocaleLowerCase("es");return courses.filter(c=>{if(filter==="active"&&!c.active)return false;if(filter==="inactive"&&c.active)return false;if(filter==="essential"&&!c.is_essential)return false;return !term||`${c.name} ${c.course_key} ${c.category} ${c.description}`.toLocaleLowerCase("es").includes(term);});},[courses,search,filter]);
 const selectedCourse=courses.find(c=>c.id===selectedId)??null;const isNew=form.id===null;
 function selectCourse(c:Course){setSelectedId(c.id);setKeyTouched(true);setMessage(null);setError(null);setForm({id:c.id,course_key:c.course_key,name:c.name,description:c.description,icon:c.icon,category:c.category,active:c.active,diagnostic_available:c.diagnostic_available});}
 function startNewCourse(){setSelectedId(null);setForm(emptyForm);setKeyTouched(false);setMessage(null);setError(null);}
 function updateName(value:string){setForm(cur=>({...cur,name:value,course_key:cur.id===null&&!keyTouched?slugify(value):cur.course_key}));}
 async function saveCourse(event:FormEvent){event.preventDefault();setSaving(true);setMessage(null);setError(null);try{const cleanKey=form.course_key.trim();const cleanName=form.name.trim();if(!cleanName)throw new Error("Escribe el nombre del curso.");if(!cleanKey)throw new Error("El curso necesita un identificador interno.");const{data,error:saveError}=await supabase.rpc("admin_save_course",{p_course_id:form.id,p_course_key:cleanKey,p_name:cleanName,p_description:form.description.trim(),p_icon:form.icon.trim()||"📚",p_category:form.category.trim()||"General",p_active:form.active,p_diagnostic_available:form.diagnostic_available});if(saveError)throw saveError;setMessage(form.id?"✅ Curso actualizado correctamente.":"✅ Curso creado. Ahora puedes construir su diagnóstico en el apartado de abajo.");await load(data as string);}catch(e){setError(friendlyError(e));}finally{setSaving(false);}}
 if(!ready)return<section className="panel"><div className="empty-state">Cargando catálogo...</div></section>;if(!canManage)return null;
 return <section className={`panel ${styles.wrapper}`}>
  <div className={styles.header}><div><p className="eyebrow">Administración</p><h2>📚 Gestionar cursos</h2><p className="muted-copy">Crea materias y luego diseña su examen en Constructor de diagnósticos.</p></div><button className="primary-button" type="button" onClick={startNewCourse}>＋ Nuevo curso</button></div>
  <div className={styles.layout}><aside className={styles.catalogPanel}><label className={styles.fieldLabel}>Buscar curso<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nombre, categoría o clave..." /></label><div className={styles.filters}>{([["all","Todos"],["active","Activos"],["inactive","Inactivos"],["essential","Esenciales"]] as const).map(([v,l])=><button key={v} className={filter===v?styles.filterActive:styles.filterButton} type="button" onClick={()=>setFilter(v)}>{l}</button>)}</div><div className={styles.courseList}>{visibleCourses.map(c=><button key={c.id} type="button" className={`${styles.courseButton} ${selectedId===c.id?styles.courseButtonActive:""}`} onClick={()=>selectCourse(c)}><div className={styles.courseTitleRow}><strong>{c.icon} {c.name}</strong><span className={c.active?styles.activeBadge:styles.inactiveBadge}>{c.active?"Activo":"Inactivo"}</span></div><span>{c.category}</span><small>{c.course_key}</small><div className={styles.badges}>{c.is_essential&&<span>🌱 Esencial</span>}{c.diagnostic_available&&<span>🧠 Diagnóstico</span>}</div></button>)}</div></aside>
  <div className={styles.editorPanel}>{selectedCourse?.is_essential?<div className={styles.essentialView}><div className={styles.essentialIcon}>{selectedCourse.icon}</div><p className="eyebrow">Curso protegido del sistema</p><h3>{selectedCourse.name}</h3><p>{selectedCourse.description||"Sin descripción."}</p><div className={styles.infoGrid}><div><small>Categoría</small><strong>{selectedCourse.category}</strong></div><div><small>Clave</small><strong>{selectedCourse.course_key}</strong></div><div><small>Obligatorio</small><strong>{selectedCourse.mandatory_days??365} días</strong></div><div><small>Diagnóstico</small><strong>{selectedCourse.diagnostic_available?"Disponible":"No disponible"}</strong></div></div><div className={styles.systemNote}>🌱 Puedes editar su examen en el Constructor de diagnósticos sin alterar la inscripción automática.</div></div>:
  <form className={styles.form} onSubmit={saveCourse}><div className={styles.formHeading}><div><p className="eyebrow">{isNew?"Nuevo curso":"Editar curso"}</p><h3>{isNew?"Crear materia":form.name||"Curso"}</h3></div></div><div className={styles.twoColumns}><label className={styles.fieldLabel}>Icono<input value={form.icon} maxLength={16} onChange={e=>setForm(c=>({...c,icon:e.target.value}))} /></label><label className={styles.fieldLabel}>Categoría<input list="course-categories" value={form.category} onChange={e=>setForm(c=>({...c,category:e.target.value}))}/><datalist id="course-categories">{categories.map(c=><option key={c} value={c}/>)}</datalist></label></div><label className={styles.fieldLabel}>Nombre del curso<input value={form.name} onChange={e=>updateName(e.target.value)} required /></label><label className={styles.fieldLabel}>Identificador interno<input value={form.course_key} onChange={e=>{setKeyTouched(true);setForm(c=>({...c,course_key:slugify(e.target.value)}));}} disabled={!isNew} required/><small>{isNew?"Se genera automáticamente.":"Se mantiene fijo para proteger historial y diagnósticos."}</small></label><label className={styles.fieldLabel}>Descripción<textarea value={form.description} onChange={e=>setForm(c=>({...c,description:e.target.value}))}/></label><div className={styles.settingsGrid}><label className={styles.toggleCard}><input type="checkbox" checked={form.active} onChange={e=>setForm(c=>({...c,active:e.target.checked}))}/><span><strong>Curso activo</strong><small>Visible y accesible para estudiantes.</small></span></label><label className={styles.toggleCard}><input type="checkbox" checked={form.diagnostic_available} onChange={e=>setForm(c=>({...c,diagnostic_available:e.target.checked}))}/><span><strong>Diagnóstico inicial</strong><small>Actívalo cuando el examen tenga niveles y preguntas. También se activa automáticamente al añadir una pregunta.</small></span></label></div>{message&&<div className="auth-message auth-success">{message}</div>}{error&&<div className="auth-message auth-error">{error}</div>}<div className={styles.actions}><button className="primary-button" disabled={saving}>{saving?"Guardando...":isNew?"Crear curso":"Guardar cambios"}</button>{!isNew&&<button className="secondary-button" type="button" onClick={startNewCourse}>Crear otro curso</button>}</div></form>}</div></div>
 </section>;
}
